import Barenco.Circuit
import Barenco.Cost
import Barenco.ControlledCircuit.Expansion
import Barenco.ControlledCircuit.ControlledZ
import Barenco.ControlledCircuit.Selected
import Barenco.ControlledCircuit.SelectedSpecial
import Barenco.Equivalence.Measurement
import Barenco.Equivalence.OperatorNorm
import Barenco.Equivalence.ControlledDistance
import Barenco.Equivalence.EventProbability
import Barenco.Equivalence.Phase
import Barenco.TwoWire.ControlledBridges
import Barenco.OneQubit.CircuitBridge
import Barenco.OneQubit.Lemma43
import Barenco.OneQubit.Pauli
import Barenco.OneQubit.Roots
import Barenco.OneQubit.CoherentRoots
import Barenco.OneQubit.U2Euler
import Barenco.OneQubit.SelectedABC
import Barenco.State.CleanWire
import Barenco.ThreeQubit.Expansion
import Barenco.ThreeQubit.RelativePhase
import Barenco.MultiControl.Lemma71
import Barenco.MultiControl.BorrowedSemantics
import Barenco.MultiControl.BorrowedResources
import Barenco.MultiControl.FourBlock
import Barenco.MultiControl.Corollary74
import Barenco.MultiControl.RelativePhase
import Barenco.MultiControl.Corollary74Expansion
import Barenco.MultiControl.GrayExpansion
import Barenco.MultiControl.Recursive
import Barenco.MultiControl.RecursiveExpansion
import Barenco.MultiControl.Resources
import Barenco.MultiControl.Approximate
import Barenco.MultiControl.ApproximateExpansion
import Barenco.MultiControl.ApproximationResources
import Barenco.LowerBounds.BasicCircuit
import Barenco.LowerBounds.InteractionGraph
import Barenco.LowerBounds.PartitionFactorization
import Barenco.LowerBounds.ScalarObstruction
import Barenco.LowerBounds.Lemma77
import Barenco.MultiControl.LinearSpecialUnitaryPhase
import Barenco.MultiControl.CleanAncillaExpansion
import Barenco.MultiControl.LinearResources
import Barenco.Universality.ExactSynthesis
import Barenco.Universality.WidthOne
import Barenco.Universality.ZeroWidth
import Barenco.Universality.EliminationResources
import Barenco.Universality.TwoLevelResources
import Barenco.Universality.DiagonalResources
import Barenco.Universality.SynthesisResources
import Barenco.Universality.Section8BasicResources

/-!
# Kernel axiom audit

Run this module with `lake env lean Barenco/AxiomAudit.lean`. The output is copied
to `docs/axiom-audit.md` at stage boundaries.
-/

#print axioms Barenco.fromPaper_mul
#print axioms Barenco.fromPaper_mem_unitaryGroup_iff
#print axioms Barenco.evalGates_append
#print axioms Barenco.fromPaper_paperProduct
#print axioms Barenco.gate_mul_one
#print axioms Barenco.reindex_mem_unitaryGroup_iff
#print axioms Barenco.blockDiagonal_mem_unitaryGroup_iff
#print axioms Barenco.localRaw_mem_unitaryGroup
#print axioms Barenco.positiveControlledRaw_truthTable
#print axioms Barenco.cnotRaw_mulVec_basisKet
#print axioms Barenco.Primitive.positiveControlled_support_card
#print axioms Barenco.Primitive.toffoli_support_card
#print axioms Barenco.Primitive.toffoli_denotation_mulVec_basisKet
#print axioms Barenco.Circuit.eval_append
#print axioms Barenco.Circuit.eval_adjoint

/-! ## Goal 2 Stage 2: certified ordered two-wire semantics -/

#print axioms Barenco.OrderedWirePair.swap_swap
#print axioms Barenco.splitTwoWire_snd_eq_iff
#print axioms Barenco.setTwoWire_swap
#print axioms Barenco.twoWireRaw_mulVec_basisKet_eq_sum
#print axioms Barenco.twoWireRaw_mulVec
#print axioms Barenco.twoWireUnitary_mul
#print axioms Barenco.twoWireUnitary_inv
#print axioms Barenco.twoWireUnitary_mk_proof_irrel
#print axioms Barenco.twoWireUnitary_swap
#print axioms Barenco.twoWireUnitary_localUnitary_zero
#print axioms Barenco.twoWireUnitary_localUnitary_one
#print axioms Barenco.twoWireUnitary_positiveControlledUnitary_zero_one
#print axioms Barenco.twoWireUnitary_cnotUnitary_zero_one

#print axioms Barenco.GlobalPhaseEq.mul
#print axioms Barenco.BasisPhaseEq.postcompose
#print axioms Barenco.BasisPhaseEq.toBasisMeasurementEq
#print axioms Barenco.GlobalPhaseEq.toChannelEq
#print axioms Barenco.channelEq_iff_allMeasurementEq
#print axioms Barenco.ChannelEq.toBasisMeasurementEq
#print axioms Barenco.operatorDistance_unitary_mul_left
#print axioms Barenco.operatorDistance_unitary_mul_right
#print axioms Barenco.operatorDistance_mul_unitary_le
#print axioms Barenco.operatorDistance_action_le
#print axioms Barenco.operatorDistance_basisOutcomeProbability_le
#print axioms Barenco.operatorDistance_unitary_le_two
#print axioms Barenco.Circuit.cost_append
#print axioms Barenco.Circuit.cost_adjoint
#print axioms Barenco.Circuit.touchedSupport_card_le_registerWidth
#print axioms Barenco.Primitive.namedModels_reject_unclassified_of_mem
#print axioms Barenco.OneQubit.paperRy_mul
#print axioms Barenco.OneQubit.paperX_mul_paperRy_mul_paperX
#print axioms Barenco.OneQubit.ry_mem_specialUnitaryGroup
#print axioms Barenco.OneQubit.sigmaX_mul_ry_mul_sigmaX
#print axioms Barenco.OneQubit.paperA_mul_paperB_mul_paperC
#print axioms Barenco.OneQubit.paperA_mul_X_mul_paperB_mul_X_mul_paperC
#print axioms Barenco.OneQubit.specialUnitary_canonical
#print axioms Barenco.OneQubit.specialUnitary_eq_paperEuler_arg
#print axioms Barenco.OneQubit.specialUnitary_exists_rz_mul_ry_mul_rz
#print axioms Barenco.OneQubit.removeGlobalPhase_det
#print axioms Barenco.OneQubit.phaseShift_mul_specialUnitaryPart
#print axioms Barenco.OneQubit.unitary_exists_phaseShift_mul_rz_mul_ry_mul_rz
#print axioms Barenco.OneQubit.specialUnitary_exists_paperABC
#print axioms Barenco.OneQubit.specialUnitary_exists_columnChronologicalABC
#print axioms Barenco.OneQubit.unitaryRoot_pow
#print axioms Barenco.OneQubit.unitaryRoot_pow_two_pow
#print axioms Barenco.OneQubit.sigmaXUnitary_eq_pauliX
#print axioms Barenco.OneQubit.paperY_mem_unitaryGroup
#print axioms Barenco.OneQubit.sigmaY_mem_unitaryGroup
#print axioms Barenco.ControlledCircuit.targetBlockRaw_mul
#print axioms Barenco.ControlledCircuit.eval_controlledABCCircuit_eq_iff
#print axioms Barenco.ControlledCircuit.controlledSU2Circuit_correct_iff
#print axioms Barenco.ControlledCircuit.controlledABCCircuit_oneQubitCNOTCost
#print axioms Barenco.ControlledCircuit.controlledScalarUnitary_eq_localControl
#print axioms Barenco.ControlledCircuit.controlledU2Circuit_exists
#print axioms Barenco.ControlledCircuit.controlledU2Circuit_oneQubitCNOTCost
#print axioms Barenco.ControlledCircuit.pauliConjugate_eq_sigmaX_mul_symmetricEuler
#print axioms Barenco.ControlledCircuit.twoCNOTFamily_iff
#print axioms Barenco.ControlledCircuit.oneCNOTFamily_iff
#print axioms Barenco.ControlledCircuit.twoCNOTCircuit_oneQubitCNOTCost
#print axioms Barenco.ControlledCircuit.oneCNOTCircuit_oneQubitCNOTCost
#print axioms Barenco.ControlledCircuit.controlledVMacroU2Circuit_exists
#print axioms Barenco.ControlledCircuit.controlledVMacroU2Circuit_oneQubitCNOTCost
#print axioms Barenco.ControlledCircuit.eval_expandedVMacroU2Circuit_eq_macro
#print axioms Barenco.ControlledCircuit.eval_expandedVMacroU2Circuit_eq_controlledU2Circuit
#print axioms Barenco.ControlledCircuit.expanded_and_mergedVMacroU2Circuit_oneQubitCNOTCosts
#print axioms Barenco.ControlledCircuit.controlledZUnitary_swap
#print axioms Barenco.ThreeQubit.cnotRaw_commute_localRaw
#print axioms Barenco.ThreeQubit.eval_doubleControlledViaSquareCircuit_pow_two
#print axioms Barenco.ThreeQubit.eval_doubleControlledRootCircuit
#print axioms Barenco.ThreeQubit.eval_doubleControlledExpansion20Circuit_eq_16
#print axioms Barenco.ThreeQubit.doubleControlledUnitary_has_sixteenPrimitiveCircuit
#print axioms Barenco.ThreeQubit.wMatrix_eq_ry_pi
#print axioms Barenco.ThreeQubit.paperW_eq_paperPhase_mul_paperY
#print axioms Barenco.ThreeQubit.wUnitary_eq_phaseShift_mul_sigmaY
#print axioms Barenco.ThreeQubit.eval_relativePhaseToffoliACircuit
#print axioms Barenco.ThreeQubit.eval_relativePhaseToffoliBCircuit
#print axioms Barenco.ThreeQubit.eval_relativePhaseToffoliACircuit_eq_BCircuit
#print axioms Barenco.ThreeQubit.relativeToffoliUnitary_sq
#print axioms Barenco.ThreeQubit.relativePhaseToffoliACircuit_mulVec_basisKet
#print axioms Barenco.ThreeQubit.controlledWUnitary_mulVec_basisKet
#print axioms Barenco.ThreeQubit.relativePhaseToffoliACircuit_basisPhaseEq_toffoli
#print axioms Barenco.ThreeQubit.controlledWUnitary_basisPhaseEq_toffoli
#print axioms Barenco.ThreeQubit.relativePhaseToffoliACircuit_oneQubitCNOTCost
#print axioms Barenco.ThreeQubit.relativePhaseToffoliBCircuit_oneQubitCNOTCost
#print axioms Barenco.ControlledCircuit.targetBlockRaw_mulVec_basisKet
#print axioms Barenco.MultiControl.parityInclusionExclusionSum_formula
#print axioms Barenco.MultiControl.grayCode_isChain
#print axioms Barenco.MultiControl.nodup_grayCode
#print axioms Barenco.MultiControl.runXorEdges_grayCNOTEdges
#print axioms Barenco.MultiControl.OrderedControlLayout.all_controls_iff
#print axioms Barenco.MultiControl.grayRootProduct_selectedRoot_formula
#print axioms Barenco.MultiControl.eval_grayCNOTCircuit_mulVec_basisKet
#print axioms Barenco.MultiControl.eval_grayControlledViaRootCircuit
#print axioms Barenco.MultiControl.eval_grayControlledCircuit
#print axioms Barenco.MultiControl.grayControlledViaRootCircuit_kindCounts
#print axioms Barenco.MultiControl.eval_fourBitGrayCircuit
#print axioms Barenco.Primitive.namedModels_reject_toffoli
#print axioms Barenco.MultiControl.InwardLadderLayout.slotCount_le_ambientWidth
#print axioms Barenco.MultiControl.InwardLadderLayout.halfLadderCircuit_gateCount
#print axioms Barenco.MultiControl.InwardLadderLayout.inwardLadderCircuit_toffoliCount
#print axioms Barenco.MultiControl.InwardLadderLayout.inwardLadderUpdate_eq_update
#print axioms Barenco.MultiControl.InwardLadderLayout.eval_inwardLadderCircuit
#print axioms Barenco.MultiControl.InwardLadderLayout.touchedSupport_inwardLadderCircuit_subset
#print axioms Barenco.MultiControl.InwardLadderLayout.inwardLadderCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.FourBlockLayout.sourceSplit_bounds
#print axioms Barenco.MultiControl.FourBlockLayout.logicalWidth_le_ambientWidth
#print axioms Barenco.MultiControl.FourBlockLayout.fourBlockUpdate_eq_update
#print axioms Barenco.MultiControl.FourBlockLayout.eval_fourBlockCircuit
#print axioms Barenco.MultiControl.FourBlockLayout.fourBlockSubstitutionCircuit_gateCount
#print axioms Barenco.MultiControl.FourBlockLayout.eval_fourBlockSubstitutionCircuit
#print axioms Barenco.MultiControl.FourBlockLayout.aInwardLadderLayout_orderedControlLayout
#print axioms Barenco.MultiControl.FourBlockLayout.eval_corollary74Circuit
#print axioms Barenco.MultiControl.FourBlockLayout.corollary74Circuit_toffoliCount
#print axioms Barenco.MultiControl.FourBlockLayout.targetWire_not_mem_corollary74AImplementation_touchedSupport
#print axioms Barenco.MultiControl.FourBlockLayout.balancedTails_add_seven
#print axioms Barenco.MultiControl.FourBlockLayout.balancedLayout_dataControlCount
#print axioms Barenco.MultiControl.FourBlockLayout.balancedLayout_targetWire_not_mem_aImplementation_touchedSupport
#print axioms Barenco.MultiControl.FourBlockLayout.eval_balancedCorollary74Circuit
#print axioms Barenco.MultiControl.FourBlockLayout.balancedCorollary74Circuit_gateCount
#print axioms Barenco.MultiControl.FourBlockLayout.balancedCorollary74Circuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.InwardLadderLayout.relativeHalfPhaseExponent_succ
#print axioms Barenco.MultiControl.InwardLadderLayout.eval_relativeHalfLadderCircuit_sq
#print axioms Barenco.MultiControl.InwardLadderLayout.eval_relativeHalfLadderCircuit_mulVec_basisKet
#print axioms Barenco.MultiControl.InwardLadderLayout.eval_relativeInwardLadderCircuit_mulVec_basisKet
#print axioms Barenco.MultiControl.InwardLadderLayout.eval_hybridInwardLadderCircuit
#print axioms Barenco.MultiControl.FourBlockLayout.eval_adjoint_relativeCorollary74AImplementation_mulVec_basisKet
#print axioms Barenco.MultiControl.FourBlockLayout.relativeCorollary74A_phase_after_ABA
#print axioms Barenco.MultiControl.FourBlockLayout.eval_relativeCorollary74Circuit
#print axioms Barenco.MultiControl.FourBlockLayout.balancedRelativeCorollary74RelativeOccurrenceCount
#print axioms Barenco.MultiControl.FourBlockLayout.eval_balancedRelativeCorollary74Circuit
#print axioms Barenco.MultiControl.eval_exactToffoliExpansionCircuit
#print axioms Barenco.MultiControl.exactToffoliExpansionCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.InwardLadderLayout.eval_expandedHybridInwardLadderCircuit
#print axioms Barenco.MultiControl.InwardLadderLayout.expandedHybridInwardLadderCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.FourBlockLayout.eval_expandedRelativeCorollary74Circuit
#print axioms Barenco.MultiControl.FourBlockLayout.expandedRelativeCorollary74Circuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.FourBlockLayout.eval_balancedExpandedRelativeCorollary74Circuit
#print axioms Barenco.MultiControl.FourBlockLayout.balancedExpandedRelativeCorollary74Circuit_oneQubitCount
#print axioms Barenco.MultiControl.FourBlockLayout.balancedExpandedRelativeCorollary74Circuit_cnotCount
#print axioms Barenco.MultiControl.FourBlockLayout.balancedExpandedRelativeCorollary74Circuit_gateCount
#print axioms Barenco.MultiControl.FourBlockLayout.balancedExpandedRelativeCorollary74Circuit_oneQubitCNOTCost
#print axioms Barenco.ControlledCircuit.eval_selectedControlledU2Circuit
#print axioms Barenco.ControlledCircuit.selectedControlledU2Circuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_expandedGrayControlledViaRootCircuit
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_expandedGrayControlledCircuit
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedGrayControlledCircuit_gateCount
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedGrayControlledCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_sixControlExpandedGrayCircuit
#print axioms Barenco.MultiControl.OrderedControlLayout.sixControlExpandedGrayCircuit_gateCount
#print axioms Barenco.MultiControl.OrderedControlLayout.all_controls_iff_prefixEnabled_and_last
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_recursiveViaSquareCircuit_pow_two
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_recursiveRootCircuit
#print axioms Barenco.MultiControl.OrderedControlLayout.recursiveViaSquareCircuit_gateCount
#print axioms Barenco.MultiControl.OrderedControlLayout.recursiveViaSquareCircuit_kindCount
#print axioms Barenco.MultiControl.OrderedControlLayout.recursiveViaSquareCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_zeroControlCircuit
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_recursiveSubstitutionCircuit_pow_two
#print axioms Barenco.MultiControl.OrderedControlLayout.recursiveSubstitutionCircuit_cost_of_eq
#print axioms Barenco.MultiControl.OrderedControlLayout.recursivePrefixFourBlockLayout_dirtyWire
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_expandedRecursivePrefixXCircuit
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedRecursivePrefixXCircuit_gateCount
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_recursivePrimitiveCircuit
#print axioms Barenco.MultiControl.OrderedControlLayout.recursivePrimitiveCircuit_gateCount_succ
#print axioms Barenco.MultiControl.OrderedControlLayout.recursivePrimitiveCircuit_oneQubitCount
#print axioms Barenco.MultiControl.OrderedControlLayout.recursivePrimitiveCircuit_cnotCount
#print axioms Barenco.MultiControl.OrderedControlLayout.recursivePrimitiveCircuit_gateCount
#print axioms Barenco.MultiControl.OrderedControlLayout.recursivePrimitiveCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.OrderedControlLayout.recursivePrimitiveCircuit_oneQubitCNOTCost_eq_resource
#print axioms Barenco.MultiControl.recursivePrimitiveTotalCountAtWidth_eq
#print axioms Barenco.MultiControl.recursivePrimitiveTotalCountAtWidth_succ
#print axioms Barenco.MultiControl.recursivePrimitiveTotalCountAtWidth_le_sq
#print axioms Barenco.MultiControl.recursivePrimitiveTotalCount_isBigOWith_depth
#print axioms Barenco.MultiControl.recursivePrimitiveTotalCount_isBigOWith_width
#print axioms Barenco.OneQubit.selectedColumnABCFactors_active
#print axioms Barenco.ControlledCircuit.eval_selectedControlledSU2Circuit
#print axioms Barenco.ControlledCircuit.selectedControlledSU2Circuit_oneQubitCNOTCost
#print axioms Barenco.fixedWireEmbed_restrict
#print axioms Barenco.fixedWireSubspace_factorization
#print axioms Barenco.positiveControlledUnitary_mulVec_mem_cleanZeroSubspace
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_expandedPrefixTargetXCircuit
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedPrefixTargetXCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_linearABCCircuit_of_products
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_linearSU2Circuit
#print axioms Barenco.MultiControl.OrderedControlLayout.linearABCCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_expandedLinearSU2Circuit
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedLinearSU2Circuit_gateCount
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedLinearSU2Circuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.OrderedControlLayout.fullyControlledWPhase_input
#print axioms Barenco.MultiControl.OrderedControlLayout.fullyControlledW_basisPhaseEq_pauliX
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedLinearWSU2Circuit_basisMeasurementEq
#print axioms Barenco.MultiControl.OrderedControlLayout.cleanAncillaTargetProduct_eq_of_aux_true
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_cleanAncillaCircuit_mulVec_basisKet
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_cleanAncillaCircuit_mulVec_of_mem_cleanZero
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_cleanAncillaCircuit_factorization
#print axioms Barenco.MultiControl.OrderedControlLayout.cleanAncillaCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_expandedCleanAncillaCircuit_eq_cleanAncilla
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_expandedCleanAncillaCircuit_mulVec_of_mem_cleanZero
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_expandedCleanAncillaCircuit_factorization
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedCleanAncillaCircuit_oneCleanAncillaContract
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedCleanAncillaCircuit_oneQubitCNOTCost_eq_resource
#print axioms Barenco.MultiControl.linearSU2TotalCountAtWidth_eq
#print axioms Barenco.MultiControl.linearSU2TotalCount_isBigOWith_width
#print axioms Barenco.MultiControl.cleanAncillaTotalCountAtWidth_eq
#print axioms Barenco.MultiControl.cleanAncillaTotalCount_isBigOWith_width

/-! ## Stage 9: approximation and resource selection -/

#print axioms Barenco.OneQubit.unitaryRootScalar_pow_two_succ_sq
#print axioms Barenco.OneQubit.powerTwoRoot_succ_sq
#print axioms Barenco.OneQubit.powerTwoRoot_operatorDistance_one_le
#print axioms Barenco.ControlledCircuit.norm_targetBlockRaw
#print axioms Barenco.ControlledCircuit.operatorDistance_positiveControlledUnitary_one_eq
#print axioms Barenco.eventProjection_norm_le
#print axioms Barenco.eventReflection_inner_self_re
#print axioms Barenco.abs_eventProbability_sub_eventProbability_le_of_norm_eq
#print axioms Barenco.operatorDistance_eventProbability_le
#print axioms Barenco.operatorDistance_eventProbability_le_two_mul
#print axioms Barenco.MultiControl.OrderedControlLayout.positiveControlledUnitary_eq_residual_mul_eval_truncatedFrom
#print axioms Barenco.MultiControl.OrderedControlLayout.operatorDistance_truncatedRecursiveCircuitFrom_eq_residual
#print axioms Barenco.MultiControl.OrderedControlLayout.operatorDistance_truncatedRecursiveCircuit_le
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_completedTruncatedRecursiveCircuit
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_expandedTruncatedRecursiveCircuitFrom
#print axioms Barenco.MultiControl.OrderedControlLayout.operatorDistance_expandedTruncatedRecursiveCircuit_le
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedTruncatedRecursiveCircuit_gateCount
#print axioms Barenco.MultiControl.OrderedControlLayout.expandedTruncatedRecursiveCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.OrderedControlLayout.eval_completedExpandedTruncatedRecursiveCircuit
#print axioms Barenco.MultiControl.OrderedControlLayout.completedExpandedTruncatedRecursiveCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.principalRootBoundDepth_le_iff
#print axioms Barenco.MultiControl.capacity_lt_principalRootBoundDepth_iff
#print axioms Barenco.MultiControl.truncatedRecursiveTotalCount_isBigOWith_width_mul_depth
#print axioms Barenco.MultiControl.OrderedControlLayout.operatorDistance_epsilonSynthesisPrimitiveCircuit_le
#print axioms Barenco.MultiControl.OrderedControlLayout.epsilonSynthesisPrimitiveCircuit_eventProbability_le
#print axioms Barenco.MultiControl.OrderedControlLayout.epsilonSynthesisPrimitiveCircuit_gateCount
#print axioms Barenco.MultiControl.OrderedControlLayout.epsilonSynthesisPrimitiveCircuit_oneQubitCNOTCost
#print axioms Barenco.MultiControl.epsilonSynthesisTotalCountAtWidth_le
#print axioms Barenco.MultiControl.epsilonSynthesisTotalCountAtWidth_lt_logarithmic

/-! ## Stage 10: exact lower bounds -/

#print axioms Barenco.LowerBounds.BasicCircuit.eval_erase
#print axioms Barenco.LowerBounds.BasicCircuit.gateCount_eq_oneQubitCount_add_cnotCount
#print axioms Barenco.LowerBounds.BasicCircuit.erase_oneQubitCNOTCost
#print axioms Barenco.LowerBounds.BasicCircuit.interactionGraph_edgeFinset_card_le_cnotCount
#print axioms Barenco.LowerBounds.BasicCircuit.cnotCount_lowerBound_of_interactionGraph_connected
#print axioms Barenco.LowerBounds.BasicCircuit.targetComponent_compl_nonempty_of_not_connected
#print axioms Barenco.LowerBounds.TensorFactorsAcross.mul
#print axioms Barenco.LowerBounds.cnotRaw_tensorLocalOnCut_of_mem
#print axioms Barenco.LowerBounds.BasicCircuit.eval_tensorFactorsAcross_targetComponent
#print axioms Barenco.LowerBounds.isScalarQubitMatrix_iff_entries
#print axioms Barenco.LowerBounds.isScalarQubitMatrix_coe_iff_exists_phaseShiftUnitary
#print axioms Barenco.LowerBounds.isScalarQubitMatrix_of_tensorFactorsAcross_positiveControlledRaw
#print axioms Barenco.LowerBounds.not_tensorFactorsAcross_fullyControlled_of_not_scalar
#print axioms Barenco.LowerBounds.BasicCircuit.interactionGraph_connected_of_eval_fullyControlled
#print axioms Barenco.LowerBounds.BasicCircuit.fullyControlled_cnotCount_lowerBound
#print axioms Barenco.LowerBounds.BasicCircuit.fullyControlled_cnotCount_lowerBound_of_not_exists_phaseShiftUnitary
#print axioms Barenco.LowerBounds.BasicCircuit.fullyControlled_gateCount_lowerBound
#print axioms Barenco.LowerBounds.BasicCircuit.fullyControlled_oneQubitCNOTCost_lowerBound

/-! ## Stage 11: exact positive-width universality -/

#print axioms Barenco.Universality.givensUnitary_eliminates
#print axioms Barenco.Universality.twoLevelUnitary_mulVec_basisKet_first
#print axioms Barenco.Universality.decomposeFinUnitary_product_eq
#print axioms Barenco.Universality.decomposeFinUnitary_residual_diagonal
#print axioms Barenco.Universality.reindexUnitary_twoLevelUnitary
#print axioms Barenco.Universality.decomposeFiniteUnitary_product_eq
#print axioms Barenco.Universality.decomposeFiniteUnitary_residual_diagonal
#print axioms Barenco.Universality.length_basisPath
#print axioms Barenco.Universality.basisPath_isChain
#print axioms Barenco.Universality.eval_fullControlCircuit
#print axioms Barenco.Universality.fullControlCircuit_oneQubitCNOTCost
#print axioms Barenco.Universality.eval_patternControlledCircuit
#print axioms Barenco.Universality.patternControlledCircuit_oneQubitCNOTCost
#print axioms Barenco.Universality.eval_adjacentTwoLevelCircuit
#print axioms Barenco.Universality.eval_affinePairCircuit_first
#print axioms Barenco.Universality.eval_affinePairCircuit_second
#print axioms Barenco.Universality.affinePairCircuit_oneQubitCNOTCost
#print axioms Barenco.Universality.unitary_conjugate_twoLevelUnitary
#print axioms Barenco.Universality.eval_twoLevelCircuit
#print axioms Barenco.Universality.twoLevelCircuit_oneQubitCNOTCost
#print axioms Barenco.Universality.eval_diagonalCircuit
#print axioms Barenco.Universality.diagonalCircuit_oneQubitCNOTCost
#print axioms Barenco.Universality.eval_orderedCircuitProduct
#print axioms Barenco.Universality.cost_orderedCircuitProduct
#print axioms Barenco.Universality.eval_exactSynthesisCircuit
#print axioms Barenco.Universality.exactSynthesisCircuit_oneQubitCNOTCost
#print axioms Barenco.Universality.exact_oneQubitCNOT_universality
#print axioms Barenco.Universality.eval_widthOneCircuit
#print axioms Barenco.Universality.widthOneCircuit_oneQubitCNOTCost
#print axioms Barenco.Universality.basicCircuit_zero_eval
#print axioms Barenco.Universality.zeroWidthNegUnitary_ne_one
#print axioms Barenco.Universality.no_basicCircuit_zero_realizes_neg

/-! ## Stage 12: aggregate resources and Section 8 cost model -/

#print axioms Barenco.CostModel.arbitraryTwoQubit_controlled_eq_some_one_iff
#print axioms Barenco.CostModel.arbitraryTwoQubit_controlled_eq_none_iff
#print axioms Barenco.Circuit.arbitraryTwoQubit_cost_of_oneQubitCNOT_cost
#print axioms Barenco.Circuit.gateCount_eq_of_oneQubitCNOT_cost
#print axioms Barenco.MultiControl.OrderedControlLayout.recursiveViaSquareCircuit_arbitraryTwoQubitCost
#print axioms Barenco.MultiControl.OrderedControlLayout.recursiveViaSquareCircuit_arbitraryTwoQubitCost_of_two_le
#print axioms Barenco.ThreeQubit.doubleControlledRootCircuit_arbitraryTwoQubitCost
#print axioms Barenco.ThreeQubit.relativePhaseToffoliACircuit_arbitraryTwoQubitCost
#print axioms Barenco.ThreeQubit.relativePhaseToffoliBCircuit_arbitraryTwoQubitCost
#print axioms Barenco.MultiControl.fourBitGrayCircuit_arbitraryTwoQubitCost
#print axioms Barenco.Universality.decomposeFinUnitary_factors_length
#print axioms Barenco.Universality.decomposeFiniteUnitary_factors_length
#print axioms Barenco.Universality.decomposeQubitUnitary_factors_length
#print axioms Barenco.Universality.decomposeQubitUnitary_factors_length_succ
#print axioms Barenco.Universality.sq_succ_le_fullControlCircuitCost
#print axioms Barenco.Universality.fullControlCircuitCost_le_sq_succ
#print axioms Barenco.Universality.affinePairGateCount_le
#print axioms Barenco.Universality.canonicalAdjacentTwoLevelCircuitCost_eq
#print axioms Barenco.Universality.twoLevelCircuitCost_bounds
#print axioms Barenco.Universality.FiniteTwoLevelFactor.circuitCost_bounds
#print axioms Barenco.Universality.card_complementBasis
#print axioms Barenco.Universality.allComplementPatterns_length
#print axioms Barenco.Universality.pow_two_mul_sq_succ_le_diagonalCircuitCost
#print axioms Barenco.Universality.diagonalCircuitCost_le_pow_two_mul_sq_succ
#print axioms Barenco.Universality.choose_two_pow_succ_add_pow
#print axioms Barenco.Universality.two_mul_exactSynthesisBenchmark_le_cost
#print axioms Barenco.Universality.exactSynthesisCost_le_benchmark
#print axioms Barenco.Universality.exactSynthesisCost_bounds
#print axioms Barenco.Universality.exactSynthesisCircuit_gateCount
#print axioms Barenco.Universality.exactSynthesisCircuit_arbitraryTwoQubitCost
#print axioms Barenco.Universality.exact_arbitraryTwoQubit_universality
#print axioms Barenco.Universality.exactSynthesisCost_isBigOWith_fixedSchedule
#print axioms Barenco.Universality.exactSynthesisBenchmark_isBigOWith_cost
#print axioms Barenco.Universality.exactSynthesisCost_isTheta_fixedSchedule
