import Barenco.Cost

/-!
# Circuits generated by one-qubit gates and CNOTs

This module gives the lower-bound development a proof-carrying syntax whose
allowed primitive set is visible in its type.  A `BasicPrimitive` is either an
arbitrary certified one-qubit gate or a CNOT with distinct control and target;
there is no constructor for a macro, Toffoli, arbitrary two-qubit gate, or
unclassified full-register unitary.

Erasure uses the trusted smart constructors from `Barenco.Circuit`.  The
restricted evaluator and resource counts are defined directly on the restricted
syntax, then related exactly to the generic evaluator and cost infrastructure.
Thus later semantic lower bounds can quantify over `BasicCircuit` without
attempting to infer locality from `Primitive.kind` metadata.
-/

namespace Barenco.LowerBounds

/--
Exactly the primitive operations admitted by the paper's Sections 3--7 basic
gate model.

The inequality stored by `cnot` prevents a syntactically counted CNOT from
collapsing to a one-wire operation.
-/
inductive BasicPrimitive (n : ℕ) where
  /-- An arbitrary certified one-qubit unitary on `target`. -/
  | oneQubit (target : Fin n) (U : QubitUnitary)
  /-- A CNOT with ordered, distinct control and target wires. -/
  | cnot (control target : Fin n) (hcontrolTarget : control ≠ target)

namespace BasicPrimitive

/-- Forget the restricted witness while retaining the trusted generic primitive. -/
def erase {n : ℕ} : BasicPrimitive n → Primitive n
  | .oneQubit target U => Primitive.oneQubit target U
  | .cnot control target hcontrolTarget =>
      Primitive.cnot control target hcontrolTarget

@[simp]
theorem erase_oneQubit {n : ℕ} (target : Fin n) (U : QubitUnitary) :
    erase (.oneQubit target U) = Primitive.oneQubit target U := rfl

@[simp]
theorem erase_cnot {n : ℕ} (control target : Fin n)
    (hcontrolTarget : control ≠ target) :
    erase (.cnot control target hcontrolTarget) =
      Primitive.cnot control target hcontrolTarget := rfl

/-- Certified full-register denotation of a restricted primitive. -/
def denotation {n : ℕ} (primitive : BasicPrimitive n) : UnitaryGate n :=
  primitive.erase.denotation

@[simp]
theorem denotation_oneQubit {n : ℕ} (target : Fin n) (U : QubitUnitary) :
    denotation (.oneQubit target U) = localUnitary target U := rfl

@[simp]
theorem denotation_cnot {n : ℕ} (control target : Fin n)
    (hcontrolTarget : control ≠ target) :
    denotation (.cnot control target hcontrolTarget) =
      cnotUnitary control target hcontrolTarget := rfl

/-- One for a one-qubit primitive and zero for a CNOT. -/
def oneQubitCount {n : ℕ} : BasicPrimitive n → ℕ
  | .oneQubit _ _ => 1
  | .cnot _ _ _ => 0

/-- One for a CNOT and zero for a one-qubit primitive. -/
def cnotCount {n : ℕ} : BasicPrimitive n → ℕ
  | .oneQubit _ _ => 0
  | .cnot _ _ _ => 1

@[simp]
theorem oneQubitCount_oneQubit {n : ℕ} (target : Fin n) (U : QubitUnitary) :
    oneQubitCount (.oneQubit target U) = 1 := rfl

@[simp]
theorem oneQubitCount_cnot {n : ℕ} (control target : Fin n)
    (hcontrolTarget : control ≠ target) :
    oneQubitCount (.cnot control target hcontrolTarget) = 0 := rfl

@[simp]
theorem cnotCount_oneQubit {n : ℕ} (target : Fin n) (U : QubitUnitary) :
    cnotCount (.oneQubit target U) = 0 := rfl

@[simp]
theorem cnotCount_cnot {n : ℕ} (control target : Fin n)
    (hcontrolTarget : control ≠ target) :
    cnotCount (.cnot control target hcontrolTarget) = 1 := rfl

@[simp]
theorem oneQubitCount_add_cnotCount {n : ℕ} (primitive : BasicPrimitive n) :
    primitive.oneQubitCount + primitive.cnotCount = 1 := by
  cases primitive <;> rfl

end BasicPrimitive

/-- A chronological list containing only arbitrary one-qubit gates and CNOTs. -/
abbrev BasicCircuit (n : ℕ) := List (BasicPrimitive n)

namespace BasicCircuit

/-- Erase a restricted circuit to the existing generic circuit syntax. -/
def erase {n : ℕ} (circuit : BasicCircuit n) : Circuit n :=
  circuit.map BasicPrimitive.erase

@[simp]
theorem erase_nil (n : ℕ) : erase ([] : BasicCircuit n) = Circuit.identity n := rfl

@[simp]
theorem erase_cons {n : ℕ} (primitive : BasicPrimitive n)
    (circuit : BasicCircuit n) :
    erase (primitive :: circuit) = primitive.erase :: erase circuit := rfl

@[simp]
theorem erase_append {n : ℕ} (first second : BasicCircuit n) :
    erase (first ++ second) = Circuit.append first.erase second.erase := by
  simp [erase, Circuit.append]

/--
Certified chronological evaluator for restricted circuits.  The head executes
first, so later denotations multiply on the left.
-/
def eval {n : ℕ} : BasicCircuit n → UnitaryGate n
  | [] => 1
  | primitive :: circuit => eval circuit * primitive.denotation

@[simp]
theorem eval_nil {n : ℕ} : eval ([] : BasicCircuit n) = 1 := rfl

@[simp]
theorem eval_cons {n : ℕ} (primitive : BasicPrimitive n)
    (circuit : BasicCircuit n) :
    eval (primitive :: circuit) = eval circuit * primitive.denotation := rfl

/-- Erasure preserves the certified full-register evaluator exactly. -/
@[simp]
theorem eval_erase {n : ℕ} (circuit : BasicCircuit n) :
    Circuit.eval circuit.erase = circuit.eval := by
  induction circuit with
  | nil => rfl
  | cons primitive circuit ih =>
      simp only [erase_cons, Circuit.eval_cons, eval_cons, ih]
      rfl

/-- Chronological concatenation has the same multiplication order as `Circuit`. -/
@[simp]
theorem eval_append {n : ℕ} (first second : BasicCircuit n) :
    eval (first ++ second) = eval second * eval first := by
  rw [← eval_erase, erase_append, Circuit.eval_append]
  simp

/-- Number of arbitrary one-qubit primitive occurrences. -/
def oneQubitCount {n : ℕ} : BasicCircuit n → ℕ
  | [] => 0
  | primitive :: circuit => primitive.oneQubitCount + oneQubitCount circuit

/-- Number of CNOT primitive occurrences, including repeated wire pairs. -/
def cnotCount {n : ℕ} : BasicCircuit n → ℕ
  | [] => 0
  | primitive :: circuit => primitive.cnotCount + cnotCount circuit

/-- Total number of restricted primitive occurrences. -/
def gateCount {n : ℕ} (circuit : BasicCircuit n) : ℕ := circuit.length

@[simp]
theorem oneQubitCount_nil {n : ℕ} : oneQubitCount ([] : BasicCircuit n) = 0 := rfl

@[simp]
theorem oneQubitCount_cons {n : ℕ} (primitive : BasicPrimitive n)
    (circuit : BasicCircuit n) :
    oneQubitCount (primitive :: circuit) =
      primitive.oneQubitCount + oneQubitCount circuit := rfl

@[simp]
theorem cnotCount_nil {n : ℕ} : cnotCount ([] : BasicCircuit n) = 0 := rfl

@[simp]
theorem cnotCount_cons {n : ℕ} (primitive : BasicPrimitive n)
    (circuit : BasicCircuit n) :
    cnotCount (primitive :: circuit) = primitive.cnotCount + cnotCount circuit := rfl

@[simp]
theorem gateCount_nil {n : ℕ} : gateCount ([] : BasicCircuit n) = 0 := rfl

@[simp]
theorem gateCount_cons {n : ℕ} (primitive : BasicPrimitive n)
    (circuit : BasicCircuit n) :
    gateCount (primitive :: circuit) = gateCount circuit + 1 := by
  simp [gateCount]

@[simp]
theorem oneQubitCount_append {n : ℕ} (first second : BasicCircuit n) :
    oneQubitCount (first ++ second) = oneQubitCount first + oneQubitCount second := by
  induction first with
  | nil => simp
  | cons primitive first ih =>
      simp only [List.cons_append, oneQubitCount_cons, ih]
      omega

@[simp]
theorem cnotCount_append {n : ℕ} (first second : BasicCircuit n) :
    cnotCount (first ++ second) = cnotCount first + cnotCount second := by
  induction first with
  | nil => simp
  | cons primitive first ih =>
      simp only [List.cons_append, cnotCount_cons, ih]
      omega

@[simp]
theorem gateCount_append {n : ℕ} (first second : BasicCircuit n) :
    gateCount (first ++ second) = gateCount first + gateCount second := by
  simp [gateCount]

/-- Every restricted primitive is accounted for by exactly one named count. -/
theorem gateCount_eq_oneQubitCount_add_cnotCount {n : ℕ}
    (circuit : BasicCircuit n) :
    circuit.gateCount = circuit.oneQubitCount + circuit.cnotCount := by
  induction circuit with
  | nil => rfl
  | cons primitive circuit ih =>
      rw [gateCount_cons, ih, oneQubitCount_cons, cnotCount_cons]
      have hprimitive := primitive.oneQubitCount_add_cnotCount
      omega

/-- CNOT occurrences form a lower bound for the total number of basic gates. -/
theorem cnotCount_le_gateCount {n : ℕ} (circuit : BasicCircuit n) :
    circuit.cnotCount ≤ circuit.gateCount := by
  rw [gateCount_eq_oneQubitCount_add_cnotCount]
  omega

/-- One-qubit occurrences form a lower bound for the total number of basic gates. -/
theorem oneQubitCount_le_gateCount {n : ℕ} (circuit : BasicCircuit n) :
    circuit.oneQubitCount ≤ circuit.gateCount := by
  rw [gateCount_eq_oneQubitCount_add_cnotCount]
  omega

/-! ## Exact bridges to generic structural resources -/

@[simp]
theorem erase_oneQubitCount {n : ℕ} (circuit : BasicCircuit n) :
    Circuit.kindCount .oneQubit circuit.erase = circuit.oneQubitCount := by
  induction circuit with
  | nil => rfl
  | cons primitive circuit ih =>
      change
        List.countP
            (fun erasedPrimitive : Primitive n =>
              decide (erasedPrimitive.kind = PrimitiveKind.oneQubit))
            (primitive.erase :: BasicCircuit.erase circuit) =
          primitive.oneQubitCount + BasicCircuit.oneQubitCount circuit
      change
        List.countP
            (fun erasedPrimitive : Primitive n =>
              decide (erasedPrimitive.kind = PrimitiveKind.oneQubit))
            (BasicCircuit.erase circuit) = BasicCircuit.oneQubitCount circuit at ih
      rw [List.countP_cons, ih]
      cases primitive <;> simp [Nat.add_comm]

@[simp]
theorem erase_cnotCount {n : ℕ} (circuit : BasicCircuit n) :
    Circuit.kindCount .cnot circuit.erase = circuit.cnotCount := by
  induction circuit with
  | nil => rfl
  | cons primitive circuit ih =>
      change
        List.countP
            (fun erasedPrimitive : Primitive n =>
              decide (erasedPrimitive.kind = PrimitiveKind.cnot))
            (primitive.erase :: BasicCircuit.erase circuit) =
          primitive.cnotCount + BasicCircuit.cnotCount circuit
      change
        List.countP
            (fun erasedPrimitive : Primitive n =>
              decide (erasedPrimitive.kind = PrimitiveKind.cnot))
            (BasicCircuit.erase circuit) = BasicCircuit.cnotCount circuit at ih
      rw [List.countP_cons, ih]
      cases primitive <;> simp [Nat.add_comm]

@[simp]
theorem erase_gateCount {n : ℕ} (circuit : BasicCircuit n) :
    Circuit.gateCount circuit.erase = circuit.gateCount := by
  simp [Circuit.gateCount, erase, gateCount]

/-- The paper's one-qubit/CNOT model accepts every erased restricted circuit. -/
@[simp]
theorem erase_oneQubitCNOTCost {n : ℕ} (circuit : BasicCircuit n) :
    Circuit.cost CostModel.oneQubitCNOT circuit.erase = some circuit.gateCount := by
  induction circuit with
  | nil => rfl
  | cons primitive circuit ih =>
      cases primitive <;> simp [Circuit.addCost, gateCount, ih] <;> omega

/--
Any numeric value assigned to an erased restricted circuit by the named model is
at least its CNOT occurrence count.
-/
theorem cnotCount_le_of_erase_oneQubitCNOTCost_eq_some {n cost : ℕ}
    (circuit : BasicCircuit n)
    (hcost : Circuit.cost CostModel.oneQubitCNOT circuit.erase = some cost) :
    circuit.cnotCount ≤ cost := by
  rw [erase_oneQubitCNOTCost] at hcost
  have hgateCount : circuit.gateCount = cost := Option.some.inj hcost
  rw [← hgateCount]
  exact cnotCount_le_gateCount circuit

/-- Cost is equivalently the sum of the two exact restricted occurrence counts. -/
theorem erase_oneQubitCNOTCost_eq_counts {n : ℕ} (circuit : BasicCircuit n) :
    Circuit.cost CostModel.oneQubitCNOT circuit.erase =
      some (circuit.oneQubitCount + circuit.cnotCount) := by
  rw [erase_oneQubitCNOTCost, gateCount_eq_oneQubitCount_add_cnotCount]

end BasicCircuit

end Barenco.LowerBounds
