import Barenco.LowerBounds.BasicCircuit
import Mathlib.Combinatorics.SimpleGraph.Acyclic
import Mathlib.Combinatorics.SimpleGraph.Connectivity.Finite

/-!
# Interaction graphs for one-qubit/CNOT circuits

This module records the undirected wire-interaction graph generated by the CNOT
occurrences of a proof-carrying `BasicCircuit`.  One-qubit gates contribute no
edges.  Repeated CNOTs on the same unordered wire pair remain distinct circuit
occurrences but collapse to one graph edge, so the graph edge count is bounded
above by, rather than identified with, the CNOT occurrence count.

The target component is exposed as a finite wire set.  If the interaction graph
is disconnected, that component has a nonempty complement, and every basic gate
lies wholly inside the component or wholly outside it.  These are the structural
facts needed by the tensor-factorization proof of Barenco Lemma 7.7.
-/

namespace Barenco.LowerBounds

namespace BasicPrimitive

/-- The finite set of ambient wires named by one restricted primitive. -/
def wires {n : ℕ} : BasicPrimitive n → Finset (Fin n)
  | .oneQubit target _ => {target}
  | .cnot control target _ => {control, target}

@[simp]
theorem wires_oneQubit {n : ℕ} (target : Fin n) (U : QubitUnitary) :
    wires (.oneQubit target U) = {target} := rfl

@[simp]
theorem wires_cnot {n : ℕ} (control target : Fin n)
    (hcontrolTarget : control ≠ target) :
    wires (.cnot control target hcontrolTarget) = {control, target} := rfl

/-- A primitive does not cross `partition` when all of its wires lie on one side. -/
def DoesNotCross {n : ℕ} (partition : Finset (Fin n))
    (primitive : BasicPrimitive n) : Prop :=
  primitive.wires ⊆ partition ∨ Disjoint primitive.wires partition

end BasicPrimitive

namespace BasicCircuit

/--
The unordered endpoint pair of every CNOT occurrence, in chronological order.

Duplicates are deliberately retained here: `cnotEdges.length` is the syntactic
CNOT occurrence count.  They are removed only when the interaction graph is
formed below.
-/
def cnotEdges {n : ℕ} : BasicCircuit n → List (Sym2 (Fin n))
  | [] => []
  | .oneQubit _ _ :: circuit => cnotEdges circuit
  | .cnot control target _ :: circuit => s(control, target) :: cnotEdges circuit

@[simp]
theorem cnotEdges_nil {n : ℕ} : cnotEdges ([] : BasicCircuit n) = [] := rfl

@[simp]
theorem cnotEdges_oneQubit_cons {n : ℕ} (target : Fin n) (U : QubitUnitary)
    (circuit : BasicCircuit n) :
    cnotEdges (.oneQubit target U :: circuit) = cnotEdges circuit := rfl

@[simp]
theorem cnotEdges_cnot_cons {n : ℕ} (control target : Fin n)
    (hcontrolTarget : control ≠ target) (circuit : BasicCircuit n) :
    cnotEdges (.cnot control target hcontrolTarget :: circuit) =
      s(control, target) :: cnotEdges circuit := rfl

/-- The CNOT edge list has exactly one entry per syntactic CNOT occurrence. -/
@[simp]
theorem length_cnotEdges {n : ℕ} (circuit : BasicCircuit n) :
    circuit.cnotEdges.length = circuit.cnotCount := by
  induction circuit with
  | nil => rfl
  | cons primitive circuit ih =>
      cases primitive <;> simp [cnotCount, ih, Nat.add_comm]

/-- A CNOT occurrence contributes its unordered endpoint pair to `cnotEdges`. -/
theorem cnotEdge_mem_cnotEdges_of_mem {n : ℕ} (circuit : BasicCircuit n)
    (control target : Fin n) (hcontrolTarget : control ≠ target)
    (hmem : BasicPrimitive.cnot control target hcontrolTarget ∈ circuit) :
    s(control, target) ∈ circuit.cnotEdges := by
  induction circuit with
  | nil => simp at hmem
  | cons primitive circuit ih =>
      rcases List.mem_cons.mp hmem with hhead | htail
      · subst primitive
        simp
      · cases primitive with
        | oneQubit wire U =>
            simpa using ih htail
        | cnot first second hfirstSecond =>
            exact List.mem_cons_of_mem _ (ih htail)

/--
The simple interaction graph obtained by forgetting chronology and duplicate
CNOT endpoint pairs.
-/
def interactionGraph {n : ℕ} (circuit : BasicCircuit n) : SimpleGraph (Fin n) :=
  SimpleGraph.fromEdgeSet ↑circuit.cnotEdges.toFinset

instance instDecidableRelInteractionGraph {n : ℕ} (circuit : BasicCircuit n) :
    DecidableRel circuit.interactionGraph.Adj := by
  rw [interactionGraph]
  infer_instance

theorem interactionGraph_adj {n : ℕ} (circuit : BasicCircuit n)
    (first second : Fin n) :
    circuit.interactionGraph.Adj first second ↔
      s(first, second) ∈ circuit.cnotEdges ∧ first ≠ second := by
  simp [interactionGraph, SimpleGraph.fromEdgeSet_adj]

/-- Every CNOT occurrence makes its two distinct endpoint wires adjacent. -/
theorem interactionGraph_adj_of_cnot_mem {n : ℕ} (circuit : BasicCircuit n)
    (control target : Fin n) (hcontrolTarget : control ≠ target)
    (hmem : BasicPrimitive.cnot control target hcontrolTarget ∈ circuit) :
    circuit.interactionGraph.Adj control target := by
  rw [interactionGraph_adj]
  exact ⟨cnotEdge_mem_cnotEdges_of_mem circuit control target hcontrolTarget hmem,
    hcontrolTarget⟩

/-- Every graph edge comes from the duplicate-retaining CNOT edge list. -/
theorem interactionGraph_edgeFinset_subset_cnotEdges {n : ℕ}
    (circuit : BasicCircuit n) :
    circuit.interactionGraph.edgeFinset ⊆ circuit.cnotEdges.toFinset := by
  intro edge hedge
  have hedgeSet : edge ∈ circuit.interactionGraph.edgeSet := by
    simpa only [SimpleGraph.mem_edgeFinset] using hedge
  rw [interactionGraph, SimpleGraph.edgeSet_fromEdgeSet] at hedgeSet
  exact hedgeSet.1

/--
Duplicate-safe edge bound: the number of distinct interaction edges is at most
the number of CNOT occurrences.
-/
theorem interactionGraph_edgeFinset_card_le_cnotCount {n : ℕ}
    (circuit : BasicCircuit n) :
    circuit.interactionGraph.edgeFinset.card ≤ circuit.cnotCount := by
  calc
    circuit.interactionGraph.edgeFinset.card
        ≤ circuit.cnotEdges.toFinset.card :=
      Finset.card_le_card (interactionGraph_edgeFinset_subset_cnotEdges circuit)
    _ ≤ circuit.cnotEdges.length := circuit.cnotEdges.toFinset_card_le
    _ = circuit.cnotCount := length_cnotEdges circuit

/--
A connected CNOT interaction graph on an `n`-wire register forces at least
`n - 1` CNOT occurrences.
-/
theorem cnotCount_lowerBound_of_interactionGraph_connected {n : ℕ}
    (circuit : BasicCircuit n) (hconnected : circuit.interactionGraph.Connected) :
    n - 1 ≤ circuit.cnotCount := by
  have hvertices := hconnected.card_vert_le_card_edgeSet_add_one
  have hedges := interactionGraph_edgeFinset_card_le_cnotCount circuit
  have hvertices' : n ≤ circuit.interactionGraph.edgeFinset.card + 1 := by
    simpa [Nat.card_eq_fintype_card, SimpleGraph.edgeFinset_card] using hvertices
  omega

/-- The wires reachable from a selected target in the CNOT interaction graph. -/
def targetComponent {n : ℕ} (circuit : BasicCircuit n) (target : Fin n) :
    Finset (Fin n) :=
  Finset.univ.filter fun wire => circuit.interactionGraph.Reachable target wire

@[simp]
theorem mem_targetComponent {n : ℕ} (circuit : BasicCircuit n)
    (target wire : Fin n) :
    wire ∈ circuit.targetComponent target ↔
      circuit.interactionGraph.Reachable target wire := by
  simp [targetComponent]

@[simp]
theorem target_mem_targetComponent {n : ℕ} (circuit : BasicCircuit n)
    (target : Fin n) :
    target ∈ circuit.targetComponent target := by
  simp [targetComponent]

theorem targetComponent_nonempty {n : ℕ} (circuit : BasicCircuit n)
    (target : Fin n) :
    (circuit.targetComponent target).Nonempty :=
  ⟨target, target_mem_targetComponent circuit target⟩

/-- Adjacent wires lie on the same side of the target-component partition. -/
theorem interactionGraph_adj_mem_targetComponent_iff {n : ℕ}
    (circuit : BasicCircuit n) (target first second : Fin n)
    (hadj : circuit.interactionGraph.Adj first second) :
    first ∈ circuit.targetComponent target ↔
      second ∈ circuit.targetComponent target := by
  simp only [mem_targetComponent]
  constructor
  · intro hreach
    exact hreach.trans hadj.reachable
  · intro hreach
    exact hreach.trans hadj.symm.reachable

/--
If the interaction graph is disconnected, the component containing any selected
target omits at least one wire.
-/
theorem targetComponent_compl_nonempty_of_not_connected {n : ℕ}
    (circuit : BasicCircuit n) (target : Fin n)
    (hdisconnected : ¬circuit.interactionGraph.Connected) :
    (circuit.targetComponent target)ᶜ.Nonempty := by
  have hnotAll : ¬∀ wire, circuit.interactionGraph.Reachable target wire := by
    intro hall
    exact hdisconnected
      (circuit.interactionGraph.connected_iff_exists_forall_reachable.mpr
        ⟨target, hall⟩)
  push Not at hnotAll
  obtain ⟨wire, hwire⟩ := hnotAll
  exact ⟨wire, by simp [hwire]⟩

/--
Every primitive occurrence lies wholly in the target component or wholly in its
complement.  In particular, no one-qubit gate or CNOT crosses the induced wire
partition.
-/
theorem primitive_doesNotCross_targetComponent {n : ℕ}
    (circuit : BasicCircuit n) (target : Fin n) (primitive : BasicPrimitive n)
    (hmem : primitive ∈ circuit) :
    primitive.DoesNotCross (circuit.targetComponent target) := by
  cases primitive with
  | oneQubit wire U =>
      by_cases hwire : wire ∈ circuit.targetComponent target
      · exact Or.inl (by simpa [BasicPrimitive.wires] using hwire)
      · exact Or.inr (by simpa [BasicPrimitive.wires] using hwire)
  | cnot control cnotTarget hcontrolTarget =>
      have hadj := interactionGraph_adj_of_cnot_mem circuit control cnotTarget
        hcontrolTarget hmem
      have hsame := interactionGraph_adj_mem_targetComponent_iff circuit target
        control cnotTarget hadj
      by_cases hcontrol : control ∈ circuit.targetComponent target
      · have hcnotTarget : cnotTarget ∈ circuit.targetComponent target :=
          hsame.mp hcontrol
        apply Or.inl
        intro wire hwire
        simp only [BasicPrimitive.wires_cnot, Finset.mem_insert,
          Finset.mem_singleton] at hwire
        rcases hwire with rfl | rfl
        · exact hcontrol
        · exact hcnotTarget
      · have hcnotTarget : cnotTarget ∉ circuit.targetComponent target := by
          exact fun h => hcontrol (hsame.mpr h)
        apply Or.inr
        rw [Finset.disjoint_left]
        intro wire hwire hpartition
        simp only [BasicPrimitive.wires_cnot, Finset.mem_insert,
          Finset.mem_singleton] at hwire
        rcases hwire with rfl | rfl
        · exact hcontrol hpartition
        · exact hcnotTarget hpartition

/-- Circuit-level packaging of the no-crossing property. -/
theorem all_primitives_doNotCross_targetComponent {n : ℕ}
    (circuit : BasicCircuit n) (target : Fin n) :
    ∀ primitive ∈ circuit,
      primitive.DoesNotCross (circuit.targetComponent target) := by
  intro primitive hmem
  exact primitive_doesNotCross_targetComponent circuit target primitive hmem

end BasicCircuit

end Barenco.LowerBounds
